// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7BnW2b93Z7lImAmXXoA4l3bZRJNP8oBA',
    appId: '1:1045151563257:web:2461cadc0889c2b6045128',
    messagingSenderId: '1045151563257',
    projectId: 'baberdule',
    authDomain: 'baberdule.firebaseapp.com',
    storageBucket: 'baberdule.firebasestorage.app',
    measurementId: 'G-8HF7V4KCV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZV1UMPvEzgJjT1EKNDefU5XO2pbLUuyI',
    appId: '1:1045151563257:android:e65ba8eeb0a12a80045128',
    messagingSenderId: '1045151563257',
    projectId: 'baberdule',
    storageBucket: 'baberdule.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2aEzxe-mNodebM9gnOfjZ1-A-4Vn_F64',
    appId: '1:1045151563257:ios:39c6bb4ed68b4a8b045128',
    messagingSenderId: '1045151563257',
    projectId: 'baberdule',
    storageBucket: 'baberdule.firebasestorage.app',
    iosBundleId: 'com.xsarmiento.barberdule',
  );
}
